"use client";

import type { Metadata } from "next";
import Script from "next/script";
import { TonConnectUIProvider } from '@tonconnect/ui-react';
import { Telegram } from "@twa-dev/types";
import Header from "@/component/Header";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

declare global {
  interface Window {
    Telegram: Telegram;
  }
};

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          id="TelegramWebApp"
          src="https://telegram.org/js/telegram-web-app.js"
          onReady={() => {
            window.Telegram?.WebApp?.ready();
          }}
        />
      </head>
      <body className={inter.className}>
        <TonConnectUIProvider
          manifestUrl="https://tomriddle7.github.io/telegram-next-mini/manifest.json"
        >
          <Header />
          {window.Telegram?.WebApp.initData}
          {children}
        </TonConnectUIProvider>
      </body>
    </html>
  );
}
